name: belajar_dart_packages_library
description: A sample command-line application with basic argument parsing.
version: 1.5.0
homepage: https://supumandart.online
repository: https://github.com/Hendri-92/belajar_dart_packages_library

environment:
  sdk: ^3.10.6

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
